const GLOBAL_PAGINATION_QUERY_NAME = "page";
const BOOKINGS_PAGINATION_QUERY_NAME = "page";

const GLOBAL_PAGINATION_RESULTS = 10;
const BOOKINGS_PAGINATION_RESULTS = 10;

const CRUD_ALLOWED_USER_EMAIL = import.meta.env.VITE_CRUD_ALLOWED_USER_EMAIL;

export {
  GLOBAL_PAGINATION_QUERY_NAME,
  BOOKINGS_PAGINATION_QUERY_NAME,
  GLOBAL_PAGINATION_RESULTS,
  BOOKINGS_PAGINATION_RESULTS,
  CRUD_ALLOWED_USER_EMAIL,
};
